---
documentation:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - '**/*.md'

root:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - '*'

github-actions:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - .github/**/*
