---
# https://pre-commit.com/#installation
default_stages: [pre-commit, pre-push]
default_language_version:
  python: python3
minimum_pre_commit_version: '3.2.0'
repos:
  - repo: meta
    hooks:
      - id: identity
        name: run identity
        description: run the identity check
      - id: check-hooks-apply
        name: check hooks apply to the repository
        description: useful when testing new hooks to see if they apply to the repository
  # Add official pre-commit hooks first
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: Trailing Whitespace
        description: Removes trailing whitespace in text files
      - id: end-of-file-fixer
        name: End of File Fixer
        description: Ensures that files end with a newline
      - id: check-yaml
        name: Check YAML
        description: Checks whether YAML files are valid
      - id: check-added-large-files
        name: Check Added Large Files
        description: Prevents adding large files to the repository

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint
        name: Markdownlint
        description: Run markdownlint on your Markdown files
        args: [--config=.github/linters/.markdown-lint.yaml]
        files: \.(md|mdown|markdown)$

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.0
    hooks:
      - id: yamllint
        name: run yamllint
        description: Lint YAML files
        args: ['-c', '.github/linters/.yamllint.yaml']
        files: \.ya?ml$

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: ['--ignore-words', '.github/linters/codespell.txt']

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks

  - repo: https://github.com/shssoichiro/oxipng
    rev: v9.1.4
    hooks:
      - id: oxipng
        args: ['-o', '4', '--strip', 'safe', '--alpha']

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
