---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # Add official pre-commit hooks first
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: Trailing Whitespace
        description: Removes trailing whitespace in text files
      - id: end-of-file-fixer
        name: End of File Fixer
        description: Ensures that files end with a newline
      - id: check-yaml
        name: Check YAML
        description: Checks whether YAML files are valid
      - id: check-added-large-files
        name: Check Added Large Files
        description: Prevents adding large files to the repository

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.42.0
    hooks:
      - id: markdownlint
        name: Markdownlint
        description: Run markdownlint on your Markdown files
        args: [--config=.github/linters/.markdown-lint.yaml]
        files: \.(md|mdown|markdown)$

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        name: run yamllint
        description: Lint YAML files
        args: ["-c", ".github/linters/.yamllint.yaml"]
        files: \.ya?ml$

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ["--ignore-words", ".github/linters/codespell.txt"]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks

  - repo: https://github.com/shssoichiro/oxipng
    rev: v9.1.2
    hooks:
      - id: oxipng
        args: ["-o", "4", "--strip", "safe", "--alpha"]

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.3
    hooks:
      - id: actionlint
