---
# https://pre-commit.com/#installation
default_stages: [pre-commit, pre-push]
default_language_version:
  # force all unspecified Python hooks to run python3
  python: python3
  # force all unspecified Node hooks to run Node.js v22.14.0 LTS
  node: 22.14.0
minimum_pre_commit_version: '3.2.0'
repos:
  - repo: meta
    hooks:
      - id: identity
        name: run identity
        description: run the identity check
      - id: check-hooks-apply
        name: check hooks apply to the repository
        description: useful when testing new hooks to see if they apply to the repository
  - repo: local
    hooks:
      - id: prettier
        name: run prettier
        description: format files with prettier
        entry: prettier --write '**/*.md' '**/*.yaml' '**/*.yml'
        files: \.ya?ml$
        language: node
        additional_dependencies: ['prettier@3.5.3']
  # Add official pre-commit hooks first
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        name: run end of file fixer
        description: ensures that files end with a newline
      - id: trailing-whitespace
        name: run trailing Whitespace
        description: removes trailing whitespace
      - id: check-added-large-files
        name: checks for adding large files
        description: prevents adding large files to the repository
      - id: check-illegal-windows-names
        name: run checks for illegal windows names
        description: checks for files that cannot be created on Windows.
      - id: check-vcs-permalinks
        name: runs check vcs permalinks
        description: check to ensure that links to vcs websites are permalinks
      - id: check-yaml
        name: run check YAML
        description: checks whether YAML files are valid
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint
        name: run markdownlint
        description: run markdownlint on your Markdown files
        args: [--config=.github/linters/.markdown-lint.yml]
        files: \.md$
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.0
    hooks:
      - id: yamllint
        name: run yamllint
        description: lint your YAML files with yamllint
        args: ['-c', '.github/linters/.yamllint.yaml']
        files: \.ya?ml$
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        name: run codespell
        description: check code for common misspellings
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks
        name: run gitleaks
        description: find secrets with Gitleaks
  - repo: https://github.com/shssoichiro/oxipng
    rev: v9.1.4
    hooks:
      - id: oxipng
        name: run oxipng
        description: multithreaded PNG optimizer written in Rust
        args: ['-o', '4', '--strip', 'safe', '--alpha']
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
        name: run actionlint
        description: static checker for GitHub Actions workflow files
