---
# https://github.com/DavidAnson/markdownlint#rules--aliases

# line-length - Line length
MD013: false

# MD033/no-inline-html
MD033: false

# MD041/first-line-heading/first-line-h1
MD041: false

# MD051/link-fragments
MD051: false
