---
  name: Pre-commit

  on: [push, pull_request]

  jobs:
    pre-commit:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4.2.2

        - name: Set up Python
          uses: actions/setup-python@v5.3.0
          with:
            python-version: '3.13'  # Specify your Python version

        - name: Set Python Version Hash
          run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> "$GITHUB_ENV"

        - name: Cache pre-commit
          uses: actions/cache@v3
          with:
            path: ~/.cache/pre-commit
            key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

        - name: Install pre-commit
          run: |
            python -m pip install --upgrade pip
            pip install pre-commit

        - name: Run pre-commit
          run: pre-commit run --all-files
